name: bomb
# Controls when the workflow will run
on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Prepare p7zip
        run: sudo apt install p7zip
      - name: Echo out some stuff
        run: |
          echo "Current folder location: $(find $HOME -maxdepth 1 -name 'aod_setup')"
          echo "Current module version: $(cat "$(find $HOME -maxdepth 1 -name 'aod_setup')/version")"
          echo "Time and Date right now (H:M D-M-Y): $(date +"%H%M-%d%m%Y")"
      - name: Zip file
        run: 7z a ModdedXGoodies-v"$(cat "$(find $HOME -maxdepth 1 -name 'aod_setup')/version")"-"$(date +"%H%M-%d%m%Y")".zip $(find $HOME -maxdepth 1 -name 'aod_setup')/module/*
      - name: Upload file to Telegram
        env: 
          FILE_TO_SEND: $(find $(find $HOME -maxdepth 1 -name 'aod_setup') -name 'ModdedXGoodies*.zip')
          TEXT_TO_SEND: $(cat "$(find $HOME -maxdepth 1 -name 'aod_setup')/changelog.md")
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          curl -4 -s -S -L -w"\n" -o- \
              -F document=@"$(find $(find $HOME -maxdepth 1 -name 'aod_setup') -name 'ModdedXGoodies*.zip')" \
              -F parse_mode='Markdown' \
              -F caption="$(cat "$(find $HOME -maxdepth 1 -name 'aod_setup')/changelog.md")" \
              -X POST https://api.telegram.org/bot${BOT_TOKEN}/sendDocument \
              -F chat_id="${CHAT_ID}"
