name: bomb
# Controls when the workflow will run
on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo out some stuff
        run: ls
