name: bomb
on:
  push:
    branches: [ "developer" ]
  pull_request:
    branches: [ "developer" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Echo out some stuff
        run: |
          file_getprop() {   grep "^$2=" "$1" | cut -d= -f2-; }
          version=$(file_getprop module.prop versionCode)
          echo "Current module version: $version"
          DATE=$(date +"%H%M-%d%m%Y")
          echo "Time and Date right now (H:M D-M-Y): $DATE"
      - name: Zip file
        run: 7z a ModdedXGoodies-v"$version"-"$DATE".zip ./module/*
      - name: upload to tg
        env:
          CHAT_ID: ${{ secrets.CHAT_ID }}
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
          COMMIT_URL: ${{ github.event.head_commit.url }}
          RUN_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          TITLE: MXG Module
        run: |
          if [ ! -z "${{ secrets.CHAT_ID }}" ] && [ ! -z "${{ secrets.BOT_TOKEN }}" ]; then
            export VERSION=$(git rev-list --count HEAD)
            bash $GITHUB_WORKSPACE/uploadtg.sh $(find . -type f -name "ModdedXGoodies*.zip")
          else
            echo "Telegram bot token is undefined, please add it to repository secrets!"
            exit 1
          fi
