name: bomb
on:
  push:
    branches: [ "hyper2" ]
  pull_request:
    branches: [ "hyper2" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build TelegramBotAPI
        run: |
              sudo apt-get update
              sudo apt-get upgrade
              sudo apt-get install make git zlib1g-dev libssl-dev gperf cmake g++
              git clone --recursive https://github.com/tdlib/telegram-bot-api.git
              cd telegram-bot-api
              rm -rf build
              mkdir build
              cd build
              cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=.. ..
              cmake --build . --target install
              cd ../..
              ls -l telegram-bot-api/bin/telegram-bot-api*
              
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: tgbotapi
          path: telegram-bot-api/bin/telegram-bot-api
